name: Build Deep Cleaner APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Root Gradle Files
      run: |
        # Создаем корневой build.gradle
        echo "buildscript { repositories { google(); mavenCentral() }; dependencies { classpath 'com.android.tools.build:gradle:8.2.0'; classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0' } }" > build.gradle
        echo "allprojects { repositories { google(); mavenCentral() } }" >> build.gradle
        
        # Подключаем твою реальную папку DeepCleaner вместо app
        echo "include ':DeepCleaner'" > settings.gradle
        echo "rootProject.name = 'DeepCleaner'" >> settings.gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.2
        generate-job-summary: false

    - name: Run Android Build
      run: |
        gradle wrapper --gradle-version 8.2
        chmod +x gradlew
        ./gradlew :DeepCleaner:assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DeepCleaner-APK
        path: DeepCleaner/build/outputs/apk/debug/DeepCleaner-debug.apk
